"""
The cyberInverters model shows the impacts of inverter hacks on a feeder including
system voltages, regulator actions, and capacitor responses. It leverages PyMAGIC, which
is a computational framework for deep Reinforcement Learning and control experiments for
the distributed grid, developed by LBNL.
"""


import os
import json
import re
import subprocess
from pathlib import Path
from shutil import copy2

import numpy as np
import pandas as pd
import yaml

from omf.models import __neoMetaModel__
from omf.models.__neoMetaModel__ import *


# Model metadata
modelName, template = __neoMetaModel__.metadata(__file__)
tooltip = "The cyberInverters model shows the impacts of inverter hacks on a feeder including system voltages, regulator actions, and capacitor responses."
hidden = False

# - This points to the python environment that has already installed the requirements for PyMAGIC
PYMAGIC_VENV_PYTHON = str(Path(omf.omfDir).resolve().parent.parent / 'PyMAGIC' / '.venv' / 'bin' / 'python')
# - This points to the "main" entrypoint for PyMAGIC, which for our purposes is Run_simulation.py
PYMAGIC_ENTRYPOINT = Path(omf.omfDir).resolve().parent.parent / 'PyMAGIC' / 'scripts' / 'simulation' / 'Run_simulation.py'

# - By default, we scale the per-unit values generated by PyMAGIC into residential 120 V values
_BASE_DISPLAY_VOLTAGE = 120


def new(model_dir):
    '''Create a new instance of this model. Returns true on success, false on failure.'''
    topology = 'ieee37'
    #topology = 'ieee37_attack'
    #topology = 'ieee123'
    #topology = 'ieee123_attack'
    topology_dir = Path(omf.omfDir) / 'static' / 'testFiles' / 'pyMAGIC' / topology
    try:
        # - Not all topologies contain batteries
        bsd_breakpoints_str = ''
        if (topology_dir / 'BSD_breakpoints.csv').exists():
            with (topology_dir / 'BSD_breakpoints.csv').open() as f:
                bsd_breakpoints_str = f.read()
        bsd_str = ''
        if (topology_dir / 'BSD_data.csv').exists():
            with (topology_dir / 'BSD_data.csv').open() as f:
                bsd_str = f.read()
        bsd_settings_str = ''
        if (topology_dir / 'BSD_settings.csv').exists():
            with (topology_dir / 'BSD_settings.csv').open() as f:
                bsd_settings_str = f.read()
        # - Not all topologies contain PV
        # - Add a "_pv" suffix to every column in PV_breakpoints.csv, PV_data.csv, and PV_settings.csv if it isn't already there because PyMAGIC requires
        #   it
        pv_breakpoints_str = ''
        if (topology_dir / 'PV_breakpoints.csv').exists():
            pv_breakpoints_df = pd.read_csv(topology_dir / 'PV_breakpoints.csv')
            pv_breakpoints_df.columns = [c if c.endswith('_pv') else f'{c}_pv' for c in pv_breakpoints_df.columns]
            pv_breakpoints_str = pv_breakpoints_df.to_csv(index=False)
        pv_str = ''
        if (topology_dir / 'PV_data.csv').exists():
            pv_df = pd.read_csv(topology_dir / 'PV_data.csv')
            pv_df.columns = [c if c.endswith('_pv') else f'{c}_pv' for c in pv_df.columns]
            pv_str = pv_df.to_csv(index=False)
        pv_settings_str = ''
        if (topology_dir / 'PV_settings.csv').exists():
            pv_settings_df = pd.read_csv(topology_dir / 'PV_settings.csv')
            pv_settings_df.columns = [c if c.endswith('_pv') else f'{c}_pv' for c in pv_settings_df.columns]
            pv_settings_str = pv_settings_df.to_csv(index=False)
        with (topology_dir / 'config.yaml').open() as f:
            config_str = f.read()
        with (topology_dir / 'load_data.csv').open() as f:
            load_str = f.read()
        with (topology_dir / 'plot.yaml').open() as f:
            plot_str = f.read()
        with (topology_dir / 'sensor.yaml').open() as f:
            sensor_str = f.read()
        with (topology_dir / 'sim.yaml').open() as f:
            sim_str = f.read()
        with (topology_dir / 'train.yaml').open() as f:
            train_str = f.read()
        with (topology_dir / 'KPI.yaml').open() as f:
            kpi_str = f.read()
        # - Load the duration and start timestep from sim.yaml to show the user
        sim_cfg = yaml.safe_load(sim_str)
        default_inputs = {
            'simStartDate': '2019-07-01T00:00:00Z',
            'duration': str(sim_cfg['simulation_time']),
            'durationUnits': 'seconds',
            'start': str(sim_cfg['warmup_time']),
            'feederName1': topology,
            'circuitFilename': f'{topology}.dss',
            'modelType': modelName,
            'zipCode': '59001',
            'bsdBreakpointsFilename': 'BSD_breakpoints.csv',
            'bsdBreakpointsFile': bsd_breakpoints_str,
            'bsdDataFilename': 'BSD_data.csv',
            'bsdDataFile': bsd_str,
            'bsdSettingsFilename': 'BSD_settings.csv',
            'bsdSettingsFile': bsd_settings_str,
            'configFilename': 'config.yaml',
            'configFile': config_str,
            'loadDataFilename': 'load_data.csv',
            'loadDataFile': load_str,
            'plotFilename': 'plot.yaml',
            'plotFile': plot_str,
            'pvBreakpointsFilename': 'PV_breakpoints.csv',
            'pvBreakpointsFile': pv_breakpoints_str,
            'pvDataFilename': 'PV_data.csv',
            'pvDataFile': pv_str,
            'pvSettingsFilename': 'PV_settings.csv',
            'pvSettingsFile': pv_settings_str,
            'sensorFilename': 'sensor.yaml',
            'sensorFile': sensor_str,
            'simFilename': 'sim.yaml',
            'simFile': sim_str,
            'trainFilename': 'train.yaml',
            'trainFile': train_str,
            'kpiFilename': 'KPI.yaml',
            'kpiFile': kpi_str,
            # - TODO: get a trained defense agent/tuning from LBNL. This value is a placeholder
            'defenseAgentNames': 'policy_ieee37_imbalance_sample_feb2023',
        }
        neometamodel_was_created = __neoMetaModel__.new(model_dir, default_inputs)
        copy2(topology_dir / f'{topology}.omd', Path(model_dir) / f'{topology}.omd')
    except:
        return False
    return neometamodel_was_created


def work(model_dir, input_dict):
    '''Run PyMAGIC, then parse its outputs to display in cyberInverters.html.'''
    model_dir = Path(model_dir)
    pymagic_input_dir = model_dir / 'pymagic_input'
    pymagic_input_dir.mkdir(parents=True, exist_ok=True)
    file_field_pairs = [
        ('bsdBreakpointsFilename', 'bsdBreakpointsFile'),
        ('bsdDataFilename', 'bsdDataFile'),
        ('bsdSettingsFilename', 'bsdSettingsFile'),
        ('configFilename', 'configFile'),
        ('loadDataFilename', 'loadDataFile'),
        ('plotFilename', 'plotFile'),
        ('pvBreakpointsFilename', 'pvBreakpointsFile'),
        ('pvDataFilename', 'pvDataFile'),
        ('pvSettingsFilename', 'pvSettingsFile'),
        ('sensorFilename', 'sensorFile'),
        ('simFilename', 'simFile'),
        ('trainFilename', 'trainFile'),
        ('kpiFilename', 'kpiFile')
    ]
    # - Copy every required file from allInputData.json into the pymagic_input directory
    #   - Optional files, like battery files, are skipped if the file content is an empty string
    for name_key, content_key in file_field_pairs:
        if input_dict.get(name_key) and input_dict.get(content_key):
            (pymagic_input_dir / input_dict[name_key]).write_text(input_dict[content_key])

    # - Manually copy the DSS file from the static directory to the input directory (Maybe because the DSS formatting would get messed up if we copied the
    #   .dss file into allInputData.json like the rest of the files?)
    copy2(Path(omf.omfDir) / 'static' / 'testFiles' / 'pyMAGIC' / input_dict['feederName1'] / input_dict['circuitFilename'],

        pymagic_input_dir / input_dict['circuitFilename'])
    # - The omf_observer_federate.py must receive some additional metadata about the circuit and the only way to pass it is via a file
    circuit_metadata = {
        'ieee123': {'default_connection': 'wye', 'connection_exceptions': {},
                    'substation_buses': {'swing': '150', 'downline': '150r'}},
        'ieee123_attack': {'default_connection': 'wye', 'connection_exceptions': {},
                    'substation_buses': {'swing': '150', 'downline': '150r'}},
        'ieee37':  {'default_connection': 'delta', 'connection_exceptions': {'sourcebus': 'wye'},
                    'substation_buses': {'swing': '799', 'downline': '799r'}},
        'ieee37_attack':  {'default_connection': 'delta', 'connection_exceptions': {'sourcebus': 'wye'},
                    'substation_buses': {'swing': '799', 'downline': '799r'}},
    }
    with open(pymagic_input_dir / 'bus_connection_type.json', 'w') as f:
        json.dump(circuit_metadata[input_dict['feederName1']], f, indent=4)
    update_pymagic_inputs(input_dict, pymagic_input_dir)
    run_pymagic(model_dir)

    return parse_pymagic_outputs(model_dir, input_dict)


def update_pymagic_inputs(input_dict, pymagic_input_dir):
    '''Update pymagic input files with user input from cyberInverters.html.'''
    sim_path = pymagic_input_dir / 'sim.yaml'
    text = sim_path.read_text()
    # - (?m) sets ^/$ on each line of the entire text file
    text, n = re.subn(r'(?m)^simulation_time:.*$', f'simulation_time: {input_dict["duration"]}', text)
    if n != 1:
        raise ValueError(f'expected exactly 1 simulation_time line in {sim_path}, found {n}')
    text, n = re.subn(r'(?m)^warmup_time:.*$', f'warmup_time: {input_dict["start"]}', text)
    if n != 1:
        raise ValueError(f'expected exactly 1 warmup_time line in {sim_path}, found {n}')
    sim_path.write_text(text)


def run_pymagic(model_dir):
    '''Call PyMAGIC via a subprocess.'''
    omf_data_dir = str(model_dir)
    omf_config_dir = str(model_dir / 'pymagic_input')
    omf_save_dir = str(model_dir / 'pymagic_output')
    omf_cfg_file = str(model_dir / 'pymagic_input' / 'final_config.yaml')
    os.makedirs(omf_save_dir, exist_ok=True)
    # - Pass paths to the PyMAGIC subprocess so that PyMAGIC reads from and writes to the intended model subdirectories
    env = {
        **os.environ,
        'PYMAGIC_CONFIG_DIR': omf_config_dir,
        'PYMAGIC_DATA_DIR': omf_data_dir,
        'PYMAGIC_OUTPUT_DIR': omf_save_dir,
        'PYMAGIC_CFG_FILE': omf_cfg_file
    }
    # - The helics wheel statically links libstdc++ into libhelics.so and exports that runtime's symbols. Torch dynamically links the system libstdc++.
    #   With both in one process, helics's exported old symbols can win symbol resolution over the real runtime and the process segfaults. LD_PRELOAD puts
    #   the system libstdc++ first in the symbol search order so every library binds to the one newest runtime.
    system_libstdcpp = Path('/usr/lib/x86_64-linux-gnu/libstdc++.so.6')
    if 'LD_PRELOAD' not in env and system_libstdcpp.exists():
        env['LD_PRELOAD'] = str(system_libstdcpp)
    subprocess.run([PYMAGIC_VENV_PYTHON, PYMAGIC_ENTRYPOINT], env=env, check=True)


def parse_pymagic_outputs(model_dir, input_dict):
    """Read PyMAGIC's output files and format them for cyberInverters.html."""
    model_dir = Path(model_dir)
    simulation_outputs_dir = list((model_dir / 'pymagic_output' / 'simulation').iterdir())[0]
    nreca_dir = simulation_outputs_dir / 'nreca'
    df_pow = pd.read_csv(nreca_dir / 'substation_power.csv')
    df_imb = pd.read_csv(nreca_dir / 'phase_imbalance.csv')
    df_reg = pd.read_csv(nreca_dir / 'regulator_taps.csv')
    df_busv = pd.read_csv(nreca_dir / 'bus_voltages.csv')
    df_meter = pd.read_csv(nreca_dir / 'meter_voltages.csv')
    df_trans = pd.read_csv(nreca_dir / 'transmission_voltage.csv')
    warmup = int(input_dict['start'])
    df_pow_pwm = _get_post_warmup_df(df_pow, warmup)
    df_imb_pwm = _get_post_warmup_df(df_imb, warmup)
    df_reg_pwm = _get_post_warmup_df(df_reg, warmup)
    df_busv_pwm = _get_post_warmup_df(df_busv, warmup)
    df_meter_pwm = _get_post_warmup_df(df_meter, warmup)
    df_trans_pwm = _get_post_warmup_df(df_trans, warmup)
    duration = len(df_pow_pwm)

    out = {}
    # - The starting timestamp is set to be simStartDate + warmup_seconds
    start_dt = pd.Timestamp(input_dict['simStartDate']) + pd.Timedelta(seconds=warmup)
    out['timeStamps'] = pd.date_range(start_dt, periods=duration, freq='1s').strftime('%Y-%m-%d %H:%M:%S%z').tolist()

    # - Generate data for the "Energy Balance" and "Power Profile" graphs
    #   - In PyMAGIC, "DG Output (W)" is positive when generators are producing power
    out['Consumption'] = {
        'realPower': df_pow_pwm['Power Substation (W)'].tolist(),
        'apparentPower': df_pow_pwm['Apparent Power Substation (VA)'].tolist(),
        'reactivePower': df_pow_pwm['Reactive Power Substation (V)'].tolist(),
        'losses': df_pow_pwm['Losses Total (W)'].tolist(),
        'realDG': df_pow_pwm['DG Output (W)'].tolist(),
    }
    out['powerFactor'] = df_pow_pwm['Substation Power Factor (%)'].tolist()

    # - Generate data for the "Transmission Voltage" chart
    out['swingVoltage'] = df_trans_pwm['swingVoltage'].tolist()
    out['downlineNodeVolts'] = df_trans_pwm['downlineNodeVolts'].tolist()
    # - Generate data for the phase voltages at the first node at the regulator
    #   - These are unselected by default in the Transmission Voltage graph
    out['downlineNodeVoltsPerPhase'] = {
        col.split('_', 1)[1]: df_trans_pwm[col].tolist()
        for col in df_trans_pwm.columns if col.startswith('downline_')
    }

    # - Generate data for the "Triplex Meter Voltage Summary" chart
    #   - By "triplex meter", we really just mean the voltage at a bus that has a load (i.e. the voltages at buses without loads are not included)
    out['allMeterVoltages'] = {
        k: (df_meter_pwm[k] * _BASE_DISPLAY_VOLTAGE).tolist()
        for k in ('Min', 'Mean', 'Max')
    }

    # - Generate data for the "Triplex Meter Voltage Detail" chart
    #   - Recall that bus_voltages.csv contains the per-unit voltage magnitude of every phase at every bus at every timestep
    #   - Wye buses/loads (e.g. "150_a") contain L-N voltages
    #   - Delta buses/loads (e.g. "799_ab" contain L-L voltages
    #       - The "Triplex Meter Voltage Detail" chart only displays single phases, so for delta loads: A=ab, B=bc, C=ac
    mags = {col: df_busv_pwm[col].to_numpy() for col in df_busv_pwm.columns if col != 'time'}
    out['Bus_Voltages'] = _build_bus_voltages(mags)

    # - Generate data for the "Triplex Meter Imbalances" chart
    #   - Buses that have single-phase loads have no phase imbalance, so those buses aren't rendered in the HTML. 
    #   - phase_imbalance.csv contains empty columns for single-phase loaded buses, so those columns are removed
    imb = df_imb_pwm.drop(columns='time').dropna(axis=1, how='all')
    out['voltageImbalances'] = imb.astype(object).where(imb.notna(), None).to_dict('list')

    # - Generate data for the "Triplex Meter Oscillation" chart
    out['oscillation_kpi_bus_oscillation_voltage'] = _build_oscillation_outputs(
        simulation_outputs_dir / 'logs' / 'OpenDSS_Federate_oscillation_KPI.csv', warmup)

    # - Generate data for the "Regulator Tap Changes" chart
    out['Regulator_Outputs'] = _build_regulator_outputs(df_reg_pwm)

    # - Generate data for the "Inverter Outputs" chart
    out['Inverter_Outputs'] = _build_inverter_outputs(
        simulation_outputs_dir / 'logs' / 'PV_Inverter_Federate_pv_injections.csv',
        warmup, mags,
    )

    # - Generate data for the "Battery Outputs" chart
    out['Battery_Outputs'] = _build_battery_outputs(
        simulation_outputs_dir / 'logs' / 'BSD_Inverter_Federate_bsd_injections.csv',
        simulation_outputs_dir / 'logs' / 'bsd_inverter_logs' / 'bsd_inverter_seg0.csv',
        warmup,
    )

    out['Capacitor_Outputs'] = {}
    out['switchStates'] = {}

    out['maxVoltBand'] = []
    out['minVoltBand'] = []
    out['oscillation_kpi'] = {}
    out['oscillation_kpi_area_under_curve'] = {}
    out['unbalance_kpi'] = {}
    out['stdout'] = ''

    return out


def _get_post_warmup_df(df, warmup):
    '''Drop the first <warmup> rows and reindex from 0.'''
    return df.iloc[warmup:].reset_index(drop=True)


def _build_bus_voltages(mags):
    '''Convert the per-unit, per-bus, per-phase PyMAGIC voltage magnitudes into scaled voltages and format the data for HTML.'''
    pymagic_to_html_mapping = {'ab': 'A', 'bc': 'B', 'ac': 'C', 'a': 'A', 'b': 'B', 'c': 'C'}
    out = {}
    for key, arr in mags.items():
        bus, suffix = key.rsplit('_', 1)
        phase_letter = pymagic_to_html_mapping[suffix.lower()]
        out.setdefault(bus, {})[phase_letter] = (arr * _BASE_DISPLAY_VOLTAGE).tolist()
    return out


def _build_regulator_outputs(df_reg):
    '''Read regulator_taps.csv, then combine single-phase regulators into the same chart'''
    out = {}
    for col in df_reg.columns:
        if col == 'time':
            continue
        full_regname, phase = col.rsplit('_', 1)
        base_regname = full_regname[:-1] if full_regname else full_regname
        entry = out.setdefault(base_regname, {'phases': [], 'tapchanges': {}})
        if phase not in entry['phases']:
            entry['phases'].append(phase)
        entry['tapchanges'][phase] = df_reg[col].tolist()
    return out


def _parse_injection_log(csv_path, json_col, warmup):
    '''Read PV_Inverter_Federate_pv_injections.csv or BSD_Inverter_Federate_bsd_injections.csv if they exist, drop warmup rows, and format the data
    nicely.'''
    if not csv_path.exists():
        return {}
    df = pd.read_csv(csv_path)
    inverter_data = {}
    for row in df[json_col].iloc[warmup:].map(json.loads):
        for inv_name, vals in zip(row['index'], row['data']):
            inverter_data.setdefault(inv_name, []).append(list(vals))
    return inverter_data


def _build_oscillation_outputs(osc_log_path, warmup):
    '''
    opendss_federate.py writes OpenDSS_Federate_oscillation_KPI>.csv
    
    - The oscillation KPI itself tracks how much the voltage magnitude at a phase of a bus changes second-by-second while ignoring the steady-state level
      of the voltage and any slow trends in the voltage. It does this by tracking a moving average, subtracting the moving average from the current
      voltage to get a difference, and then smoothing that difference to get the KPI. The opendss_federate.py also applies a "gain" which scales the
      oscillation KPI by some magnitude.
    - We average all the phases to get a single value for each bus
    '''
    df = pd.read_csv(osc_log_path)
    rows = df['OpenDSS_Federate/oscillation_KPI'].iloc[warmup:].map(json.loads)
    osc_df = pd.DataFrame(rows.tolist())
    bus_of_node = [node.rsplit('.', 1)[0] for node in osc_df.columns]
    per_bus = osc_df.T.groupby(bus_of_node, sort=False).mean().T
    return {bus: per_bus[bus].tolist() for bus in per_bus.columns}


def _build_inverter_outputs(pv_csv_path, warmup, mags):
    """Build Inverter_Outputs from PV injection log + voltage magnitudes."""
    inverter_data = _parse_injection_log(pv_csv_path, 'PV_Inverter_Federate/pv_injections', warmup)
    out = {}
    for inv_name, time_series in inverter_data.items():
        voltage_pu = _voltage_for_inverter(inv_name, mags)
        # - Scale to desired display voltage
        voltage = [v * _BASE_DISPLAY_VOLTAGE for v in voltage_pu]
        # - Convert from kW/kVAR to W and VAR because that's what the old PyCIGAR interface used
        inj = pd.DataFrame(time_series, columns=['p_good', 'q_good', 'p_bad', 'q_bad'])
        p_real = ((inj['p_good'] + inj['p_bad']) * 1000.0).tolist()
        p_imag = ((inj['q_good'] + inj['q_bad']) * 1000.0).tolist()
        out[inv_name] = {
            'Voltage': voltage,
            'Power_Real': p_real,
            'Power_Imag': p_imag,
        }
    return out


def _voltage_for_inverter(inv_name, mags):
    '''Get the voltage magnitude time series for an inverter at a bus.

    - If it's a single-phase inverter, return the value in the voltage magnitudes dict
    - If it's a three-phase inverter, return the averaged voltage magnitude across all three phases
    '''
    if inv_name in mags:
        return mags[inv_name].tolist()
    if inv_name.endswith('_abc'):
        bus = inv_name[:-4]
        # delta bus has L-L pairs; wye bus has L-N
        keys = [f'{bus}_{p}' for p in ('ab', 'bc', 'ac')]
        if not any(k in mags for k in keys):
            keys = [f'{bus}_{p}' for p in ('a', 'b', 'c')]
        present = [mags[k] for k in keys if k in mags]
        if present:
            return pd.DataFrame(present).mean(axis=0, skipna=False).tolist()
    raise ValueError(f"inverter {repr(inv_name)} matches no column in bus_voltages.csv")


def _build_battery_outputs(bsd_inj_path, bsd_seg_path, warmup):
    '''Build Battery_Outputs from BSD injection log + SOC log.'''
    inj_data = _parse_injection_log(bsd_inj_path, 'BSD_Inverter_Federate/bsd_injections', warmup)
    out = {}

    # SOC + segment state per BSD bus
    if bsd_seg_path.exists():
        df_seg = pd.read_csv(bsd_seg_path)
        df_seg_pwm = df_seg[df_seg['time'] >= warmup].reset_index(drop=True)
    else:
        df_seg_pwm = pd.DataFrame()

    # Threshold (in kW) below which a battery is considered "standby"
    bsd_standby_threshold_kw = 0.01
    # Charge_Status enum used by cyberInverters.html battery chart yAxis
    # categories: ["discharge", "standby", "charge"] -> [0, 1, 2]
    charge_status_discharge = 0
    charge_status_standby = 1
    charge_status_charge = 2

    for bsd_name, time_series in inj_data.items():
        # - PyMAGIC sets p_good to negative when charging and sets it to positive when discharging
        inj = pd.DataFrame(time_series, columns=['p_good', 'q_good', 'p_bad', 'q_bad'])
        p_watts = (inj['p_good'] + inj['p_bad']) * 1000.0
        real_power = p_watts.tolist()
        # - charge_status is determined by the real power of the battery at a given timestep
        #   - The battery is on standby when the absolute value of the real power is less than some threshold
        #   - The battery is discharging when the real power is greater than 0 (and past the threshold)
        #   - The battery is charging when the real power is less than 0 (and past the threshold) 
        # - case_when picks the first matching condition
        charge_status = pd.Series(charge_status_charge, index=p_watts.index).case_when([
            (p_watts.abs() < bsd_standby_threshold_kw * 1000.0, charge_status_standby),
            (p_watts > 0, charge_status_discharge),
        ]).tolist()

        # - Get the state of charge from the csvs in "bsd_inverter_logs"
        seg_for_bus = df_seg_pwm[df_seg_pwm['node'] == bsd_name].sort_values('time') if not df_seg_pwm.empty else pd.DataFrame()
        if not seg_for_bus.empty:
            soc = (seg_for_bus['current_SOC'] * 100.0).tolist()
            # - Count how many times the battery went through the equivalent of a full cycle. A cycle means discharging 100% and then charging 100% (not
            #   all at once necessarily, but cumulatively)
            cycles = float(seg_for_bus['current_SOC'].diff().abs().sum() / 2.0)
        else:
            soc = [None] * len(time_series)
            cycles = 0.0

        out[bsd_name] = {
            'SOC': soc,
            'Charge_Status': charge_status,
            'Cycles': cycles,
            'Real_Power': real_power,
        }
    return out


@neoMetaModel_test_setup
def _debugging():
    """
    Run this module's local smoke tests or debugging workflow.
    """
    model_loc = Path(omf.omfDir) / 'data' / 'Model' / 'admin' / f'Automated Testing of {modelName}'
    # Blow away old test results if necessary.
    try:
        rmtree(model_loc)
    except:
        # No previous test results.
        pass
    # Create New.
    new(model_loc)
    # Pre-run.
    # __neoMetaModel__.renderAndShow(modelLoc)
    # Run the model.
    __neoMetaModel__.runForeground(model_loc)
    # Show the output.
    __neoMetaModel__.renderAndShow(model_loc)


if __name__ == '__main__':
    _debugging()