load_name: null
load_category: physical
#load_category: opendss
threshold: 10
is_smooth: true
is_fast: false
feeder_path: rhs0_1247/rhs0_1247--rdt1527
#feeder_path: rhs2_1247/rhs2_1247--rdt1262
#feeder_path: rhs2_1247/rhs2_1247--rdt1264
multiprocessing: true